2025-09-08 14:03:20,933 - MainThread - sqlmesh.core.config.connection - INFO - Creating new DuckDB adapter for data files: {'db.db'} (connection.py:316)
2025-09-08 14:03:22,058 - MainThread - sqlmesh.core.config.connection - INFO - Creating new DuckDB adapter for in-memory database (connection.py:318)
2025-09-08 14:03:22,095 - MainThread - sqlmesh.core.config.connection - INFO - Using existing DuckDB adapter due to overlapping data file: db.db (connection.py:306)
2025-09-08 14:03:26,432 - MainThread - sqlmesh.core.snapshot.evaluator - INFO - Listing data objects in schema db.sqlmesh__sqlmesh_example (evaluator.py:323)
2025-09-08 14:03:26,438 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: SELECT CURRENT_CATALOG() (base.py:2113)
2025-09-08 14:03:26,439 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: SELECT CURRENT_CATALOG() (base.py:2113)
2025-09-08 14:03:26,441 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: SELECT table_name AS name, table_schema AS schema, CASE table_type WHEN 'BASE TABLE' THEN 'table' WHEN 'VIEW' THEN 'view' WHEN 'LOCAL TEMPORARY' THEN 'table' END AS type FROM system.information_schema.tables WHERE (table_catalog = 'db' AND table_schema = 'sqlmesh__sqlmesh_example') AND table_name IN ('sqlmesh_example__covid_analysis__1734172176', 'sqlmesh_example__seed_model__2185867172', 'sqlmesh_example__incremental_model__1880815781', 'sqlmesh_example__raw_covid_data__3580553322', 'sqlmesh_example__full_model__2278521865') (base.py:2113)
2025-09-08 14:03:26,481 - MainThread - sqlmesh.core.snapshot.evaluator - INFO - Creating schema 'db.sqlmesh__sqlmesh_example' (evaluator.py:1068)
2025-09-08 14:03:26,481 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE SCHEMA IF NOT EXISTS "db"."sqlmesh__sqlmesh_example" (base.py:2113)
2025-09-08 14:03:26,486 - MainThread - sqlmesh.core.snapshot.evaluator - INFO - Creating table 'db.sqlmesh__sqlmesh_example.sqlmesh_example__raw_covid_data__3580553322' (evaluator.py:1420)
2025-09-08 14:03:26,486 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE TABLE IF NOT EXISTS "db"."sqlmesh__sqlmesh_example"."sqlmesh_example__raw_covid_data__3580553322" AS SELECT "iso_code" AS "iso_code", "location" AS "location", "date" AS "date", "new_cases" AS "new_cases", "new_cases_per_million" AS "new_cases_per_million", "new_deaths" AS "new_deaths", "new_deaths_per_million" AS "new_deaths_per_million", "people_vaccinated" AS "people_vaccinated", "people_fully_vaccinated" AS "people_fully_vaccinated", "total_boosters" AS "total_boosters" FROM READ_CSV_AUTO('Data/OWID_COVID19_DATA.csv', "header" = TRUE, "all_varchar" = TRUE) AS "_q_0" WHERE FALSE LIMIT 0 (base.py:2113)
2025-09-08 14:03:26,774 - MainThread - sqlmesh.core.plan.evaluator - INFO - Execution failed for node SnapshotId<"db"."sqlmesh_example"."raw_covid_data": 641952641> (evaluator.py:285)
Traceback (most recent call last):
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\utils\concurrency.py", line 227, in sequential_apply_to_dag
    fn(node)
    ~~^^^^^^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\utils\concurrency.py", line 165, in <lambda>
    lambda s_id: fn(snapshots_by_id[s_id]),
                 ~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\snapshot\evaluator.py", line 377, in <lambda>
    lambda s: self._create_snapshot(
              ~~~~~~~~~~~~~~~~~~~~~^
        s,
        ^^
    ...<4 lines>...
        allow_destructive_snapshots=allow_destructive_snapshots,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\snapshot\evaluator.py", line 834, in _create_snapshot
    self._execute_create(
    ~~~~~~~~~~~~~~~~~~~~^
        snapshot=snapshot,
        ^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        dry_run=dry_run,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\snapshot\evaluator.py", line 1102, in _execute_create
    evaluation_strategy.create(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        table_name=table_name,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
        physical_properties=rendered_physical_properties,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\snapshot\evaluator.py", line 1445, in create
    self.adapter.ctas(
    ~~~~~~~~~~~~~~~~~^
        table_name,
        ^^^^^^^^^^^
    ...<9 lines>...
        column_descriptions=model.column_descriptions if is_table_deployable else None,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\engine_adapter\shared.py", line 302, in internal_wrapper
    return func(*list_args, **kwargs)
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\engine_adapter\base.py", line 542, in ctas
    return self._create_table_from_source_queries(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        table_name,
        ^^^^^^^^^^^
    ...<5 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\engine_adapter\base.py", line 762, in _create_table_from_source_queries
    self._create_table(
    ~~~~~~~~~~~~~~~~~~^
        schema if schema else table,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\engine_adapter\base.py", line 800, in _create_table
    self.execute(
    ~~~~~~~~~~~~^
        self._build_create_table_exp(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<12 lines>...
        )
        ^
    )
    ^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\engine_adapter\base.py", line 2110, in execute
    self._execute(sql, **kwargs)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\engine_adapter\base.py", line 2116, in _execute
    self.cursor.execute(sql, **kwargs)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
duckdb.duckdb.BinderException: Binder Error: Column "iso_code" referenced that exists in the SELECT clause - but this column cannot be referenced before it is defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\plan\evaluator.py", line 270, in _push
    self.snapshot_evaluator.create(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        snapshots_to_create,
        ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
        on_complete=self.console.update_creation_progress,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\snapshot\evaluator.py", line 355, in create
    self._create_snapshots(
    ~~~~~~~~~~~~~~~~~~~~~~^
        snapshots_to_create=snapshots_to_create,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        allow_destructive_snapshots=allow_destructive_snapshots,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\snapshot\evaluator.py", line 375, in _create_snapshots
    concurrent_apply_to_snapshots(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        snapshots_to_create,
        ^^^^^^^^^^^^^^^^^^^^
    ...<8 lines>...
        self.ddl_concurrent_tasks,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\utils\concurrency.py", line 163, in concurrent_apply_to_snapshots
    return concurrent_apply_to_dag(
        dag if not reverse_order else dag.reversed,
    ...<2 lines>...
        raise_on_error=raise_on_error,
    )
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\utils\concurrency.py", line 198, in concurrent_apply_to_dag
    return sequential_apply_to_dag(dag, fn, raise_on_error)
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\utils\concurrency.py", line 233, in sequential_apply_to_dag
    raise error
sqlmesh.utils.concurrency.NodeExecutionFailedError: Execution failed for node SnapshotId<"db"."sqlmesh_example"."raw_covid_data": 641952641>
2025-09-08 14:03:26,787 - MainThread - sqlmesh.core.context - INFO - Plan application failed. (context.py:1459)
Traceback (most recent call last):
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\utils\concurrency.py", line 227, in sequential_apply_to_dag
    fn(node)
    ~~^^^^^^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\utils\concurrency.py", line 165, in <lambda>
    lambda s_id: fn(snapshots_by_id[s_id]),
                 ~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\snapshot\evaluator.py", line 377, in <lambda>
    lambda s: self._create_snapshot(
              ~~~~~~~~~~~~~~~~~~~~~^
        s,
        ^^
    ...<4 lines>...
        allow_destructive_snapshots=allow_destructive_snapshots,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\snapshot\evaluator.py", line 834, in _create_snapshot
    self._execute_create(
    ~~~~~~~~~~~~~~~~~~~~^
        snapshot=snapshot,
        ^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        dry_run=dry_run,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\snapshot\evaluator.py", line 1102, in _execute_create
    evaluation_strategy.create(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        table_name=table_name,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
        physical_properties=rendered_physical_properties,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\snapshot\evaluator.py", line 1445, in create
    self.adapter.ctas(
    ~~~~~~~~~~~~~~~~~^
        table_name,
        ^^^^^^^^^^^
    ...<9 lines>...
        column_descriptions=model.column_descriptions if is_table_deployable else None,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\engine_adapter\shared.py", line 302, in internal_wrapper
    return func(*list_args, **kwargs)
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\engine_adapter\base.py", line 542, in ctas
    return self._create_table_from_source_queries(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        table_name,
        ^^^^^^^^^^^
    ...<5 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\engine_adapter\base.py", line 762, in _create_table_from_source_queries
    self._create_table(
    ~~~~~~~~~~~~~~~~~~^
        schema if schema else table,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\engine_adapter\base.py", line 800, in _create_table
    self.execute(
    ~~~~~~~~~~~~^
        self._build_create_table_exp(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<12 lines>...
        )
        ^
    )
    ^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\engine_adapter\base.py", line 2110, in execute
    self._execute(sql, **kwargs)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\engine_adapter\base.py", line 2116, in _execute
    self.cursor.execute(sql, **kwargs)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
duckdb.duckdb.BinderException: Binder Error: Column "iso_code" referenced that exists in the SELECT clause - but this column cannot be referenced before it is defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\plan\evaluator.py", line 270, in _push
    self.snapshot_evaluator.create(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        snapshots_to_create,
        ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
        on_complete=self.console.update_creation_progress,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\snapshot\evaluator.py", line 355, in create
    self._create_snapshots(
    ~~~~~~~~~~~~~~~~~~~~~~^
        snapshots_to_create=snapshots_to_create,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        allow_destructive_snapshots=allow_destructive_snapshots,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\snapshot\evaluator.py", line 375, in _create_snapshots
    concurrent_apply_to_snapshots(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        snapshots_to_create,
        ^^^^^^^^^^^^^^^^^^^^
    ...<8 lines>...
        self.ddl_concurrent_tasks,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\utils\concurrency.py", line 163, in concurrent_apply_to_snapshots
    return concurrent_apply_to_dag(
        dag if not reverse_order else dag.reversed,
    ...<2 lines>...
        raise_on_error=raise_on_error,
    )
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\utils\concurrency.py", line 198, in concurrent_apply_to_dag
    return sequential_apply_to_dag(dag, fn, raise_on_error)
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\utils\concurrency.py", line 233, in sequential_apply_to_dag
    raise error
sqlmesh.utils.concurrency.NodeExecutionFailedError: Execution failed for node SnapshotId<"db"."sqlmesh_example"."raw_covid_data": 641952641>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\context.py", line 1451, in apply
    self._apply(plan, circuit_breaker)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\context.py", line 2046, in _apply
    self._scheduler.create_plan_evaluator(self).evaluate(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        plan.to_evaluatable(), circuit_breaker=circuit_breaker
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\plan\evaluator.py", line 136, in evaluate
    self._push(plan, snapshots, deployability_index_for_creation)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\h.boulaayad\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlmesh\core\plan\evaluator.py", line 288, in _push
    raise PlanError("Plan application failed.")
sqlmesh.utils.errors.PlanError: Plan application failed.
2025-09-08 14:03:26,800 - MainThread - root - INFO - Shutting down the event dispatcher (dispatcher.py:159)
